# Generated by Django 3.2.9 on 2021-11-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mznapl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, unique=True)),
                ('url', models.CharField(max_length=128, unique=True)),
                ('note', models.CharField(max_length=128)),
            ],
        ),
    ]
