# Generated by Django 3.2.9 on 2021-11-30 08:56

from django.db import migrations, models
import mznapl.models.base.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('mznapl', '0002_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=128)),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, mznapl.models.base.mixins.AutoSlugMixin),
        ),
    ]
