# Generated by Django 3.2.9 on 2021-11-30 09:27

from django.db import migrations, models
import mznapl.models.base.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('mznapl', '0003_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('body', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('body', models.TextField()),
                ('tag', models.CharField(choices=[('blog', 'Blog'), ('note', 'Note')], max_length=32)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, mznapl.models.base.mixins.AutoSlugMixin),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, unique=True),
        ),
    ]
