# Generated by Django 3.2.9 on 2021-11-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mznapl', '0004_auto_20211130_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestbookentry',
            options={'verbose_name': 'Guestbook entry', 'verbose_name_plural': 'Guestbook entries'},
        ),
    ]
