# Generated by Django 3.2.9 on 2021-11-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mznapl', '0005_alter_guestbookentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
