# Generated by Django 3.2.9 on 2021-11-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mznapl', '0006_page_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('blog', 'Blog'), ('note', 'Note'), ('poetry', 'Poetry'), ('recipe', 'Recipe'), ('art', 'Art')], max_length=32),
        ),
    ]
