# Generated by Django 3.2.9 on 2021-12-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mznapl', '0007_alter_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='homepage',
            field=models.BooleanField(default=False, help_text="Should this page's content be displayed as the homepage?"),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(help_text='What should this page say? You should use HTML tags.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Should this page be hidden from the main navigation menu?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, help_text='The URL identifier for the page. Leave blank to auto-generate.', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='The title of the page', max_length=128, unique=True),
        ),
    ]
