# Generated by Django 3.2.9 on 2021-12-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mznapl', '0008_auto_20211201_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='hidden',
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_nav',
            field=models.BooleanField(default=False, help_text='Should this page show up as a link in the main navigation bar?'),
        ),
    ]
