# Generated by Django 3.2.9 on 2021-12-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mznapl', '0009_auto_20211201_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='show_in_nav',
            field=models.BooleanField(db_index=True, default=False, help_text='Should this page show up as a link in the main navigation bar?'),
        ),
    ]
